### ISSUE TITLE
Error with Complie

### ISSUE THREAD

**Issue by theside9** [EndCredits/android_kernel_xiaomi_sm7350#1]
......
  GEN     .version
  CHK     include/generated/compile.h
  LTO     vmlinux.o
  MODPOST vmlinux.o
WARNING: "embms_tm_multicast_recv" [vmlinux] is a static EXPORT_SYMBOL
WARNING: "tsens_mtc_reset_history_counter" [vmlinux] is a static EXPORT_SYMBOL
  MODINFO modules.builtin.modinfo
  LD      .tmp_vmlinux.kallsyms1
ld.lld: error: undefined symbol: get_hw_version_platform
>>> referenced by qmi.c:945 (../drivers/soc/qcom/icnss2/qmi.c:945)
>>>               vmlinux.o:(icnss_wlfw_bdf_dnld_send_sync)
>>> referenced by qmi.c:548 (../drivers/net/wireless/cnss2/qmi.c:548)
>>>               vmlinux.o:(cnss_wlfw_bdf_dnld_send_sync)

ld.lld: error: undefined symbol: get_hw_country_version
>>> referenced by qmi.c:946 (../drivers/soc/qcom/icnss2/qmi.c:946)
>>>               vmlinux.o:(icnss_wlfw_bdf_dnld_send_sync)
>>> referenced by qmi.c:547 (../drivers/net/wireless/cnss2/qmi.c:547)
>>>               vmlinux.o:(cnss_wlfw_bdf_dnld_send_sync)

ld.lld: error: undefined symbol: get_hw_version_build
>>> referenced by qmi.c:549 (../drivers/net/wireless/cnss2/qmi.c:549)
>>>               vmlinux.o:(cnss_wlfw_bdf_dnld_send_sync)

ld.lld: error: undefined symbol: get_hw_version_major
>>> referenced by qmi.c:550 (../drivers/net/wireless/cnss2/qmi.c:550)
>>>               vmlinux.o:(cnss_wlfw_bdf_dnld_send_sync)

ld.lld: error: undefined symbol: get_hw_version_minor
>>> referenced by qmi.c:551 (../drivers/net/wireless/cnss2/qmi.c:551)
>>>               vmlinux.o:(cnss_wlfw_bdf_dnld_send_sync)

ld.lld: error: undefined symbol: mi_disp_register_client
>>> referenced by qti_battery_charger.c:2215 (../drivers/power/supply/qti_battery_charger.c:2215)
>>>               vmlinux.o:(battery_chg_probe)

ld.lld: error: undefined symbol: mi_disp_unregister_client
>>> referenced by qti_battery_charger.c:2283 (../drivers/power/supply/qti_battery_charger.c:2283)
>>>               vmlinux.o:(battery_chg_probe)
>>> referenced by qti_battery_charger.c:2298 (../drivers/power/supply/qti_battery_charger.c:2298)
>>>               vmlinux.o:(battery_chg_remove)
make[1]: *** [/home/lsa/sm7350Kernel/Kernel/Makefile:1202: vmlinux] Error 1
make[1]: Leaving directory '/home/lsa/sm7350Kernel/Kernel/out'
make: *** [Makefile:183: sub-make] Error 2

**Comment by theside9** [comment]
I encountered an error while compiling the kernel and would like to know how to resolve it?

**Comment by EndCredits** [comment]
该仓库已弃用，请尝试下面的仓库，该仓库兼容小米  sm8350/7350/7325 平台的设备，主要支持小米 11 青春版 ( renoir ) ，请使用

[EndCredits/android_kernel_xiaomi_sm8350](https://gitHub.com/EndCredits/android_kernel_xiaomi_sm8350)

请使用如下命令 clone 该仓库

```bash
git clone https://gitHub.com/EndCredits/android_kernel_xiaomi_sm8350 --recursive
```
并确保 Kernrl SU 子模块正确同步

```bash
cd <your kernel source>
git submodule init
git submodule update --checkout
```

并使用推荐的编译器进行编译: [Nathan's Clang](https://mirrors.edge.kernel.org/pub/tools/llvm/)

如果遇到问题请在那个仓库重新开一个 issue

----------
This repository has been deprecated. Please try this repository. It's a unified tree for Xiaomi sm8350/7350/7325 devices. Mainly support Mi 11 Lite 5G ( renoir )

[EndCredits/android_kernel_xiaomi_sm8350](https://gitHub.com/EndCredits/android_kernel_xiaomi_sm8350)

Please use following commands to clone this repository.

```bash
git clone https://gitHub.com/EndCredits/android_kernel_xiaomi_sm8350 --recursive
```
And make sure kernel su submodule has been synced correctly.

```bash
cd <your kernel source>
git submodule init
git submodule update --checkout
```

And please use a recommended compiler to build: [Nathan's Clang](https://mirrors.edge.kernel.org/pub/tools/llvm/)

If there's any problem please reopen issue in that repository.
